import { LeagueInfo } from '../types';

export const SUPPORTED_LEAGUES: LeagueInfo[] = [
  {
    id: 'soccer-all-monitored',
    name: 'All Monitored Competitions',
    sport: 'soccer',
    slug: 'monitored-all',
    category: 'All',
    icon: 'Trophy',
  },
  {
    id: 'soccer-eng1',
    name: 'English Premier League',
    sport: 'soccer',
    slug: 'eng.1',
    category: 'England',
    icon: 'Shield',
  },
  {
    id: 'soccer-esp1',
    name: 'Spanish LaLiga',
    sport: 'soccer',
    slug: 'esp.1',
    category: 'Spain',
    icon: 'Flame',
  },
  {
    id: 'soccer-ita1',
    name: 'Italian Serie A',
    sport: 'soccer',
    slug: 'ita.1',
    category: 'Italy',
    icon: 'Shield',
  },
  {
    id: 'soccer-ger1',
    name: 'German Bundesliga',
    sport: 'soccer',
    slug: 'ger.1',
    category: 'Germany',
    icon: 'Shield',
  },
  {
    id: 'soccer-fra1',
    name: 'French Ligue 1',
    sport: 'soccer',
    slug: 'fra.1',
    category: 'France',
    icon: 'Compass',
  },
  {
    id: 'soccer-ucl',
    name: 'UEFA Champions League',
    sport: 'soccer',
    slug: 'uefa.champions',
    category: 'Europe',
    icon: 'Trophy',
  },
  {
    id: 'soccer-uel',
    name: 'UEFA Europa League',
    sport: 'soccer',
    slug: 'uefa.europa',
    category: 'Europe',
    icon: 'Trophy',
  },
  {
    id: 'soccer-uecl',
    name: 'UEFA Europa Conference League',
    sport: 'soccer',
    slug: 'uefa.europa.conf',
    category: 'Europe',
    icon: 'Trophy',
  },
  {
    id: 'soccer-usa1',
    name: 'Major League Soccer',
    sport: 'soccer',
    slug: 'usa.1',
    category: 'Americas',
    icon: 'Compass',
  },
  {
    id: 'soccer-libertadores',
    name: 'Copa Libertadores',
    sport: 'soccer',
    slug: 'conmebol.libertadores',
    category: 'Americas',
    icon: 'Trophy',
  },
  {
    id: 'soccer-fifa',
    name: 'FIFA World Cup',
    sport: 'soccer',
    slug: 'fifa.world',
    category: 'International',
    icon: 'Trophy',
  },
  {
    id: 'soccer-engfa',
    name: 'English FA Cup',
    sport: 'soccer',
    slug: 'eng.fa',
    category: 'England',
    icon: 'Award',
  },
  {
    id: 'soccer-engcup',
    name: 'English Carabao Cup',
    sport: 'soccer',
    slug: 'eng.league_cup',
    category: 'England',
    icon: 'Award',
  },
  {
    id: 'soccer-espcopadelrey',
    name: 'Spanish Copa del Rey',
    sport: 'soccer',
    slug: 'esp.copa_del_rey',
    category: 'Spain',
    icon: 'Award',
  },
  {
    id: 'soccer-ned1',
    name: 'Dutch Eredivisie',
    sport: 'soccer',
    slug: 'ned.1',
    category: 'Netherlands',
    icon: 'Shield',
  },
  {
    id: 'soccer-por1',
    name: 'Portuguese Primeira Liga',
    sport: 'soccer',
    slug: 'por.1',
    category: 'Portugal',
    icon: 'Shield',
  },
  {
    id: 'soccer-sau1',
    name: 'Saudi Pro League',
    sport: 'soccer',
    slug: 'sau.1',
    category: 'Middle East',
    icon: 'Award',
  },
  {
    id: 'soccer-afc-champions-east',
    name: 'AFC Champions League Elite East',
    sport: 'soccer',
    slug: 'afc.champions.east',
    category: 'Asia',
    icon: 'Trophy',
  },
  {
    id: 'soccer-afc-champions-west',
    name: 'AFC Champions League Elite West',
    sport: 'soccer',
    slug: 'afc.champions.west',
    category: 'Asia',
    icon: 'Trophy',
  },
  {
    id: 'soccer-nga1',
    name: 'Nigerian Professional League',
    sport: 'soccer',
    slug: 'nga.1',
    category: 'Africa',
    icon: 'Shield',
  },
  {
    id: 'soccer-uefa-super-cup',
    name: 'UEFA Super Cup',
    sport: 'soccer',
    slug: 'uefa.super_cup',
    category: 'Europe',
    icon: 'Trophy',
  },
  {
    id: 'soccer-uefa-euro',
    name: 'UEFA European Championship',
    sport: 'soccer',
    slug: 'uefa.euro',
    category: 'International',
    icon: 'Trophy',
  },
  {
    id: 'soccer-uefa-nations',
    name: 'UEFA Nations League',
    sport: 'soccer',
    slug: 'uefa.nations',
    category: 'International',
    icon: 'Trophy',
  },
  {
    id: 'soccer-caf-nations',
    name: 'Africa Cup of Nations',
    sport: 'soccer',
    slug: 'caf.nations',
    category: 'International',
    icon: 'Trophy',
  },
  {
    id: 'soccer-conmebol-america',
    name: 'Copa América',
    sport: 'soccer',
    slug: 'conmebol.america',
    category: 'International',
    icon: 'Trophy',
  },
  {
    id: 'soccer-concacaf-gold',
    name: 'Concacaf Gold Cup',
    sport: 'soccer',
    slug: 'concacaf.gold',
    category: 'International',
    icon: 'Trophy',
  },
  {
    id: 'soccer-afc-asian-cup',
    name: 'AFC Asian Cup',
    sport: 'soccer',
    slug: 'afc.asian.cup',
    category: 'International',
    icon: 'Trophy',
  },
];

export const MONITORED_LEAGUE_SLUGS = [
  'eng.1',
  'esp.1',
  'ita.1',
  'ger.1',
  'fra.1',
  'por.1',
  'ned.1',
  'bel.1',
  'tur.1',
  'gre.1',
  'nor.1',
  'swe.1',
  'sau.1',
  'usa.1',
  'eng.fa',
  'eng.league_cup',
  'esp.copa_del_rey',
  'nga.1',
  'uefa.champions',
  'uefa.europa',
  'uefa.europa.conf',
  'uefa.super_cup',
  'conmebol.libertadores',
  'afc.champions.east',
  'afc.champions.west',
  'fifa.world',
  'fifa.worldq',
  'fifa.confederations',
  'fifa.cwc',
  'uefa.euro',
  'uefa.nations',
  'uefa.euroq',
  'caf.nations',
  'caf.nations_qual',
  'conmebol.america',
  'conmebol.america_qual',
  'concacaf.gold',
  'concacaf.gold_qual',
  'concacaf.nations.league',
  'afc.asian.cup',
  'afc.cupq',
  'fifa.worldq.ofc',
];
